project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    background: orange
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Hands-on Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
      - text: "In-Class Exercises"
        menu:
          - text: "In-Class Exercise 1"
            href: "In-Class_Ex/In-Class_Ex01/In-Class_Ex01.html"
          - text: "In-Class Exercise 2"
            href: "In-Class_Ex/In-Class_Ex02/In-Class_Ex02.html"
          - text: "In-Class Exercise 3"
            href: "In-Class_Ex/In-Class_Ex03/In-Class_Ex03.html"
          - text: "In-Class Exercise 4"
            href: "In-Class_Ex/In-Class_Ex04/In-Class_Ex04.html"
          - text: "In-Class Exercise 5"
            href: "In-Class_Ex/In-Class_Ex05/In-Class_Ex05.html"
      - text: "Take-Home Exercises"
        menu:
          - text: "Take-Home Exercise 1"
            href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

