project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    background: orange
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

